### PR TITLE
Update to use v2 REST API

### PR DESCRIPTION
**Pull request by jchiare**
**Biggest Changes:**

- Merged all REST API endpoints to use v2.
- Added a new function, `get_contact_methods`, which is required in v2 to get the address of the on-call users endpoint.

**Minor Changes:**

- Created a new file (assets/js/app.js) to hold the Javascript.
- Tiny edits on the index.html page to reflect the v2 version of the property names (such as the name of the escalation policy). 
- Minor edits to the Javascript

### CODE REVIEW

**Comment by githubnocarrier** [comment]
Hi, i tried to used your new files and modification, however i don't see where i should put my token in app.js ? Any chance you could help?

**Comment by jchiare** [comment]
@githubnocarrier for sure! 

You'll want to head to the `config.js` file. (Assets folder -> js folder -> config.js)

In the config.js file, you'll need to change:

- The value of the `token` property to your [REST API key](https://support.pagerduty.com/v1/docs/using-the-api)
- The value of the `subdomain` property to your subdomain. The subdomain are the characters before the `.pagerduty.com` in your login URL. I.E: my PagerDuty account login url is jay.pagerduty.com, so my subdomain is `jay`.

Let me know if this helps or if you have further feedback

**Comment by githubnocarrier** [comment]
Very helpful thanks, it's now working.
Is there a way to instead only display who is oncall per "Escalation_policies" with a maximum level?
That's what i was using before but somehow i cant found the function anymore.

**Comment by githubnocarrier** [comment]
@jchiare That's the code i used previously to display the information :
`$(function () {
    PDJS = new PDJSobj(pdjs_settings)
    PDJS.api({
        res: "escalation_policies/on_call",
        success: function (data) {
            for (i in data.escalation_policies) {
                ep = data.escalation_policies[i]
                printf("<b> - " + ep.name + "</b><br>")
                for (j in ep.on_call) { // <- loop through all on-calls for this ep
                    u = ep.on_call[j]
                    if (u.level > 4) break; // <- only display the primaries
                    printf("<span style='background-color:rgb(153,204,0);' class='badge'>" + u.level + "</span> - <a href='mailto:" + u.user.email + "'>" + u.user.name + "</a><br>")
                }
            }
        }
    })
})`

**Comment by jchiare** [comment]
Unfortunately not possible with the out-of-box code I wrote. I think this customization should still be possible, but since the API endpoints changed, there should be changes to this customization. 

The current main function, named **update_users**, in my `app.js` file is used to get the oncall data - so you should look at modifying that function. 

Looking at the [API docs](https://v2.developer.pagerduty.com/v2/page/api-reference#!/On-Calls/get_oncalls) for the `/oncalls` endpoint (the endpoint used in the above function), there is an `escalation_level` property that is nested within each oncall object in the API response. 

If I were to implement it, I would: 

- Head to the `app.js` file. (Assets folder -> js folder -> app.js file)
- In [line 37](https://github.com/jchiare/pagerduty_oncall_dashboard/blob/master/assets/js/app.js#L37), add a conditional if statement that will continue if the current oncall object has an escalation level less than a value. In Javascript, this would look like `if (escalation_level < x){ insert-code-here }`.
- After the if statement, I'd move the code from lines 38 to 67 within the `app.js` file to inside the if statement we wrote above. This would allow the code to create the oncall user UI only if they meet the condition of `escalation_level < x`

Please note that I have not tested the above, this is just what I'd try first!

**Review by Deconstrained — APPROVED** [review]
Works splendidly; thank you for your work here!

**Pull request merged**
